# fly.toml app configuration file generated for ai-recommendation on 2025-03-14T09:23:25+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-recommendation'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = 2048
  cpu_kind = 'shared'
  cpus = 1
